# Generated by Django 4.2 on 2024-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_about_me_patient_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
