# Generated by Django 4.2 on 2024-09-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_consultation_doctor_alter_rating_review_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports'),
        ),
    ]
